// Project Actions
export const LOAD_PROJECTS_START = 'LOAD_PROJECTS_START';
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';
export const LOAD_PROJECTS_FAIL = 'LOAD_PROJECTS_FAIL';

// Lessons Actions
export const LOAD_LESSONS_START = 'LOAD_LESSONS_START';
export const LOAD_LESSONS_SUCCESS = 'LOAD_LESSONS_SUCCESS';
export const LOAD_LESSONS_FAIL = 'LOAD_LESSONS_FAIL';

// Attachments Actions
export const LOAD_ATTACHMENTS_START = 'LOAD_ATTACHMENTS_START';
export const LOAD_ATTACHMENTS_SUCCESS = 'LOAD_ATTACHMENTS_SUCCESS';
export const LOAD_ATTACHMENTS_FAIL = 'LOAD_ATTACHMENTS_FAIL';
