// Project Actions
export const LOAD_PROJECTS = 'GET_PROJECTS';
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';
export const LOAD_PROJECTS_FAIL = 'LOAD_PROJECTS_FAIL';

// Lessons Actions
export const LOAD_LESSONS = 'GET_LESSONS';
export const LOAD_LESSONS_SUCCESS = 'LOAD_LESSONS_SUCCESS';
export const LOAD_LESSONS_FAIL = 'LOAD_LESSONS_FAIL';

// Attachments Actions
export const LOAD_ATTACHMENTS = 'GET_ATTACHMENTS';
export const LOAD_ATTACHMENTS_SUCCESS = 'LOAD_ATTACHMENTS_SUCCESS';
export const LOAD_ATTACHMENTS_FAIL = 'LOAD_ATTACHMENTS_FAIL';
